config/routes.rb
Rateflikr::Application.routes.draw do
  
  resources :images

  resources :ratings

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "new" => "users#new"
  resources :users
  resources :sessions

  root :to => 'home#index'
  
  get "home/index"

  match "/about" => "home#about"  
  
  match "/best" => "home#best"

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  
  belongs_to :image
  
  attr_accessible :imageId, :rating, :image_id
  
  validates_numericality_of :image_id
  validates_numericality_of :rating
  validates_inclusion_of :rating, :in => 0..10
  
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
    @rating = Rating.find(params[:id])
    
    
    @pic = get_pic(@rating.imageId)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.json
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(params[:rating])
    @image = Image.find(@rating.image_id)
    @rating2 = @image.ratings.new(params[:rating])
    @rating2.imageId = @image.imageId

    respond_to do |format|
      if @rating2.save
        format.html { redirect_to @rating2, notice: 'Rating was successfully created.' }
        format.json { render json: @rating2, status: :created, location: @rating2 }
      else
        format.html { render action: "new" }
        format.json { render json: @rating2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.json
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :image_id %><br />
    <%= f.number_field :image_id %>
  </div>

  <div class="field">
    <%= f.label :imageId %><br />
    <%= f.number_field :imageId %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <td>image_id</td>
    <th>Imageid</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.image_id %></td>
    <td><%= rating.imageId %></td>
    <td><%= rating.rating %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<img src="<%= @pic %>">
<p>
  <b>Imageid:</b>
  <%= @rating.imageId %>
</p>

<p>
  <b>Rating:</b>
  <font size="+2" color="red"><%= @rating.rating %></font>
</p>

<h2><%= link_to 'Rate More Images!', root_path %></h2><br>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>